### ISSUE TITLE
Code snippets review #1: code files

### ISSUE THREAD

**Issue by atrisovic** [BostonUniversitySeniorDesign/21-05-Re3#15]
Hey guys sorry it took me so long, here are my thoughts:

- There is a difference in lengths in code snippets. Some have 20+ lines, and some 7-8 lines (and in some cases only 3 lines of code). I suggest making them more-or-less similar in length. For example 17+-3 lines of code (or 15+-3 is also good).
- The variety of code 'types' and 'styles' is quite good :)

**Comment by lukasrosario** [comment]
@ehungbu and @jyotsna-penumaka have edited the snippets
