### ISSUE TITLE
Points from the previous meeting

### ISSUE THREAD

**Issue by atrisovic** [BostonUniversitySeniorDesign/21-05-Re3#17]
Here are the points from the previous meeting: 

- Center title "How would you rate the readability of this code?"
- Consider changing one of the figures in the form to make it more intuitive that higher grade is good and lower grade is bad code
- Before the buttons, you could add something along the lines: "Select your rating (low grade means bad readability, high grade good readability)"
- Add progress bar or current count
- Add back button if that's not too hard

Otherwise it looks great, and very fancy :))

**Comment by lukasrosario** [comment]
Addressed in [19](https://github.com/BostonUniversitySeniorDesign/21-05-Re3/pull/19) 👍
